"""add grade and weight to assessment

Revision ID: 091ddb4ef0ee
Revises: 19c23428e6ed
Create Date: 2025-05-14 14:27:50.091811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091ddb4ef0ee'
down_revision = '19c23428e6ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.drop_column('weight')
        batch_op.drop_column('grade')

    # ### end Alembic commands ###
