"""add back data_type column to shared_data

Revision ID: 6ffaf57e2e50
Revises: 12e1491e028d
Create Date: 2025-05-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ffaf57e2e50'
down_revision = '12e1491e028d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('data_content', sa.JSON(), nullable=True))
        batch_op.drop_column('share_water')
        batch_op.drop_column('share_tasks')
        batch_op.drop_column('share_mood')
        batch_op.drop_column('share_study_progress')

    # Set default value for existing rows
    op.execute("UPDATE shared_data SET data_type = 'combined' WHERE data_type IS NULL")
    
    # Now make the column NOT NULL
    with op.batch_alter_table('shared_data', schema=None) as batch_op:
        batch_op.alter_column('data_type',
               existing_type=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('data_content',
               existing_type=sa.JSON(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shared_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_study_progress', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('share_mood', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('share_tasks', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('share_water', sa.Boolean(), nullable=True))
        batch_op.drop_column('data_content')
        batch_op.drop_column('data_type')
    # ### end Alembic commands ###
