"""Remove sleep_quality and sleep_hours columns

Revision ID: f90a5c7fdb8e
Revises: 19c130bf65b8
Create Date: 2025-05-10 00:25:55.996958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f90a5c7fdb8e'
down_revision = '19c130bf65b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_entry', schema=None) as batch_op:
        batch_op.drop_column('sleep_quality')

    with op.batch_alter_table('wellness_check', schema=None) as batch_op:
        batch_op.drop_column('sleep_hours')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wellness_check', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sleep_hours', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('mood_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sleep_quality', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
